version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.23
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.27
    - 14.14.28
    - 14.14.29
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: redis
    versions:
    - 3.1.2
  - dependency-name: bull
    versions:
    - 3.20.0
    - 3.20.1
    - 3.21.0
    - 3.21.1
    - 3.22.0
    - 3.22.1
    - 3.22.2
    - 3.22.3
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: "@nestjs/platform-express"
    versions:
    - 7.6.10
    - 7.6.11
    - 7.6.12
    - 7.6.13
    - 7.6.14
    - 7.6.7
    - 7.6.8
    - 7.6.9
  - dependency-name: connect-redis
    versions:
    - 5.0.0
    - 5.1.0
  - dependency-name: "@nestjs/config"
    versions:
    - 0.6.2
